name: openapi_dart_common
version: 2.0.0
authors:
  - Richard Vowles <richard@bluetrainsoftware.com>
homepage: https://github.com/dart-ogurets/openapi_dart_common
description: OpenAPI API common libraries so the generator doesn't generate them
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  dio: '>= 3.0.3 <4.0.0'
dev_dependencies:
  test: ^1.3.0
